# Generated by Django 4.2.21 on 2025-05-18 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_directorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=50)),
                ('parentesco', models.CharField(max_length=50)),
                ('celular1', models.CharField(blank=True, max_length=20, null=True)),
                ('celular2', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_directorio.edificio')),
            ],
        ),
    ]
