# Generated by Django 4.2.21 on 2025-05-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_directorio', '0002_directorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorio',
            name='apto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
