# Generated by Django 4.2.20 on 2026-04-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_directorio', '0003_directorio_apto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorio',
            old_name='observacion',
            new_name='informacion_adicional',
        ),
        migrations.RemoveField(
            model_name='directorio',
            name='celular1',
        ),
        migrations.RemoveField(
            model_name='directorio',
            name='celular2',
        ),
        migrations.RemoveField(
            model_name='directorio',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='directorio',
            name='nombre_apellido',
        ),
        migrations.RemoveField(
            model_name='directorio',
            name='parentesco',
        ),
        migrations.AddField(
            model_name='directorio',
            name='cedula',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='correo_propietario',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='nombre',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directorio',
            name='nombre_oficina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='numero_parqueadero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='oficina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='placa',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='torre_bloque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
