# Generated by Django 4.2.20 on 2026-04-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_directorio', '0004_rename_observacion_directorio_informacion_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
