# Generated by Django 4.2.20 on 2026-04-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_directorio', '0005_alter_directorio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorio',
            name='telefono2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
